# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: cyber
      POSTGRES_PASSWORD: manul
      POSTGRES_DB: messenger
      DATABASE_HOST: postgres
    ports:
      - 5432:5432